### ISSUE TITLE
FVM finished exit code 0

### ISSUE THREAD

**Issue by ARealPear** [marv7000/FastValveMaterial#4]
When running FastValveMaterial.py I get this:
FastValveMaterial (v221028)

[FVM] v221028 finished with exit code 0: All conversions finished.

config.md has not been edited from the default
![image](https://github.com/marv7000/FastValveMaterial/assets/69981765/8d55d1d4-bdde-4e87-a6d2-e43720bb2fc0)
![image](https://github.com/marv7000/FastValveMaterial/assets/69981765/a8ef4871-d285-4809-80f9-b00b7239d68f)
![image](https://github.com/marv7000/FastValveMaterial/assets/69981765/5cfead10-71dc-4a96-9447-e1a8db20dbab)

**Comment by marv7000** [comment]
You probably didn't adjust this line here in config.md:
![image](https://github.com/marv7000/FastValveMaterial/assets/35012873/5bca74df-786c-44d6-8be1-e187cf7b0308)

Exit code 0 means all materials matching that pattern were converted, but you don't have any with that name.
You can just change the setting to ``_n``, but I'll adjust too, because it should be like that out of the box.
